import type { StorageAdapter } from '../adapter'

export const sqliteStorageAdapter: StorageAdapter = {
  initWorkspace: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  setWorkspace: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  selectWorkspaceCandidate: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  createWorkspace: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  getWorkspaceRoot: async () => null,
  clearWorkspace: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  listKnowledgeBases: async () => [],
  createKnowledgeBase: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  deleteKnowledgeBase: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  renameKnowledgeBase: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  setKnowledgeBaseOrder: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  saveKnowledgeBaseCover: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  importKnowledgeBase: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  getLastOpenedKnowledgeBase: async () => null,
  setLastOpenedKnowledgeBase: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  listCards: async () => [],
  createCard: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  deleteCard: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  renameCard: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  ensureCard: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  countCards: async () => 0,
  openCardLocation: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  readCardMarkdown: async () => '',
  writeCardMarkdown: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  readCardLayout: async () => ({ children: undefined, edges: [] }),
  writeCardLayout: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  writeCardAsset: async () => { throw new Error('sqliteStorageAdapter not implemented') },
  readCardAsset: async () => null,
  readAppConfig: async () => ({}),
  writeAppConfig: async () => { throw new Error('sqliteStorageAdapter not implemented') },
}
